### ISSUE TITLE
Merge option crashes StructureFinder

### ISSUE THREAD

**Issue by ggontard** [dkratzert/StructureFinder#21]
StructureFinder v74.1 crashes whenever I use the merge feature, both with GUI and command-line.

Here's an example of the result in command-line :

C:\test-strf>strf_cmd --delete -d 2 -o merge.sqlite -r -m 1.sqlite
Old database size: 294 structures.
Merging table: Structure
Merging table: Residuals
Merging table: cell
Merging table: atoms
Merging table: sum_formula
Merging table: authors
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python311\Scripts\strf_cmd.exe\__main__.py", line 7, in <module>
  File "C:\Users\Geoffrey\AppData\Roaming\Python\Python311\site-packages\structurefinder\strf_cmd.py", line 214, in main
    merge_database(args)
  File "C:\Users\Geoffrey\AppData\Roaming\Python\Python311\site-packages\structurefinder\strf_cmd.py", line 194, in merge_database
    db.merge_databases(merge_file_name)
  File "C:\Users\Geoffrey\AppData\Roaming\Python\Python311\site-packages\structurefinder\searcher\database_handler.py", line 84, in merge_databases
    self.merge_table(table)
  File "C:\Users\Geoffrey\AppData\Roaming\Python\Python311\site-packages\structurefinder\searcher\database_handler.py", line 100, in merge_table
    table_size = len(self.con.execute(f"SELECT * from dba.{table_name}").fetchone())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()

I'm on Windows 10 and I installed with pip.

On a side note, thank you for fixing the exclude option in 74.1. This issue seems realted, sorry for not noticing it earlier.

**Comment by dkratzert** [comment]
Hi, thanks for reporting this. I have problems reproducing the error. Is it possible that you share the two database files with me? I will keep them confidential. Maybe two databases with only two structures are enough to reproduce the problem?

Were both files created wit StructureFinder 74.1?

**Comment by ggontard** [comment]
I deleted all files and recreated them, just in case. No luck.

I also tried with only one res file in each folder but I'm getting the same error.

I'm sending you all four files by mail. Some structures weren't published yet.
